x=input('Enter your name: ')
y=int(input('Enter your lab grade: '))
z=int(input('Enter your midterm grade: '))
w=int(input('Enter your final grade: '))
k=(y*25/100)+(z*35/100)+(w*40/100)
print('Name: ' ,x)
print('Lab: ' ,y)
print('Midterm: ' ,z)
print('Final: ' ,w)
print('Last score: ', k )